import React from 'react';
import Icon from './Icon';

export const AccountBalance = props => <Icon {...props} name="account_balance" />;
export const AddCircle = props => <Icon {...props} name="add_circle" />;
export const Alarm = props => <Icon {...props} name="alarm" />;
export const Assistant = props => <Icon {...props} name="assistant" />;
export const Brightness = props => <Icon {...props} name="brightness" />;
export const CalendarToday = props => <Icon {...props} name="calendar_today" />;
export const Camera = props => <Icon {...props} name="camera" />;
export const CameraEnhance = props => <Icon {...props} name="camera_enhance" />;
export const CameraPlus = props => <Icon {...props} name="camera_plus" />;
export const CloudVerified = props => <Icon {...props} name="cloud_verified" />;
export const DirectionsBoat = props => <Icon {...props} name="directions_boat" />;
export const DirectionsBus = props => <Icon {...props} name="directions_bus" />;
export const DirectionsCar = props => <Icon {...props} name="directions_car" />;
export const DirectionsSubway = props => <Icon {...props} name="directions_subway" />;
export const DirectionsTrain = props => <Icon {...props} name="directions_train" />;
export const Headset = props => <Icon {...props} name="headset" />;
export const Home = props => <Icon {...props} name="home" />;
export const OfflineBolt = props => <Icon {...props} name="offline_bolt" />;
export const Star = props => <Icon {...props} name="star" />;
export const ThumbUp = props => <Icon {...props} name="thumb_up" />;
export const VerifiedUser = props => <Icon {...props} name="verified_user" />;
export const Whatshot = props => <Icon {...props} name="whatshot" />;